---
services:
  fief:
    container_name: fief-server
    image: ghcr.io/fief-dev/fief:0.28.6
    command: fief run-server --port 8000
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:8000
    networks:
      - traefik

  worker:
    container_name: fief-worker
    image: ghcr.io/fief-dev/fief:0.28.6
    command: fief run-worker -p 1 -t 1
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
