---
services:
  fief:
    container_name: fief-server
    image: ghcr.io/fief-dev/fief:0.27.0
    command: fief run-server --port 8000
    env_file: stack.env
    depends_on:
      - postgres
      - redis
    expose:
      - 8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik

  worker:
    container_name: fief-worker
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-worker -p 1 -t 1
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik

volumes:
  redis_data:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /share/dockume/db/postgres/data
      o: bind
  pg_multidb:
    driver: local
    driver_opts:
      type: none
      device: /share/dockume/db/postgres/pg_multidb
      o: bind

networks:
  traefik:
    external: true
