## Static configuration
## path to place the file
## scp MODULAR/config/traefik.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/config
## scp MODULAR/config/traefik.yml sihuan@80.87.105.197:/home/sihuan/modular/dockume/traefik/config

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
  # postgresql:
  #   address: ":5432"
  # fief:
  #   address: ":8000"
  # traefik:
  #   address: ":8080"
  # portainer:
  #   address: ":9443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: /external
    watch: true

certificatesResolvers:
  simple-resolver:
    acme:
      email: sihuannewrise@gmail.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpchallenge:
        entrypoint: web

accesslog: true
# log:
#   level: DEBUG
