## scp -O -P 2222 traefik/config/dynamic/*.yml sihuan@192.168.2.72:/share/dockume/infra/traefik/dynamic
## scp -O -P 2222 traefik/config/dynamic/1_routers.yml sihuan@192.168.2.72:/share/dockume/infra/traefik/dynamic

http:
  routers:
    to-web:
      entryPoints:
        - websecure
      rule: Host(`knh.cloud`)
      service: web

    to-fief:
      entryPoints:
        - websecure
      rule: Host(`fief.knh.cloud`)
      service: fief

    to-nas:
      entryPoints:
        - websecure
      rule: Host(`nas.knh.cloud`)
      service: nas

    to-pihole:
      entryPoints:
        - websecure
      rule: Host(`pihole.knh.cloud`) && PathPrefix(`/admin`)
      service: pihole

    to-pgadmin:
      entryPoints:
        - websecure
      rule: Host(`pgadmin.knh.cloud`)
      middlewares:
        - auth
      service: pgadmin

    to-portainer:
      entryPoints:
        - websecure
      rule: Host(`portainer.knh.cloud`)
      service: portainer

    to-traefik:
      entryPoints:
        - websecure
      rule: Host(`traefik.knh.cloud`)
      middlewares:
        - auth
      service: traefik
