## scp -O -P 2222 traefik/config/dynamic/*.yml sihuan@192.168.2.72:/share/dockume/infra/traefik/dynamic
## scp -O -P 2222 traefik/config/dynamic/1_routers.yml sihuan@192.168.2.72:/share/dockume/infra/traefik/dynamic

http:
  routers:
    to-pihole:
      entryPoints:
        - websecure
      rule: Host(`knh.vgate.keenetic.pro`) && PathPrefix(`/pihole`)
      # middlewares:
      #   - auth
      service: pihole

    to-portainer:
      entryPoints:
        - websecure
      rule: Host(`knh.vgate.keenetic.pro`) && PathPrefix(`/portainer`)
      service: portainer

    to-traefik:
      entryPoints:
        - websecure
      rule: Host(`knh.vgate.keenetic.pro`) && PathPrefix(`/traefik`)
      # middlewares:
      #   - auth
      service: traefik
