## scp traefik/config/dynamic/*.yml root@192.168.2.91:/share/infra/traefik/dynamic
## scp -O -P 2222 traefik/config/dynamic/1_routers.yml sihuan@192.168.2.72:/share/dockume/infra/traefik/dynamic

http:
  routers:
    to-web:
      entryPoints:
        - websecure
      rule: Host(`knh.cloud`)
      service: web

    to-fief:
      entryPoints:
        - websecure
      rule: Host(`fief.knh.cloud`)
      service: fief

    to-nocodb:
      entryPoints:
        - websecure
      rule: Host(`nocodb.knh.cloud`)
      service: nocodb

    to-pihole:
      service: pihole
      entryPoints:
        - websecure
      rule: Host(`pihole.knh.cloud`) && PathPrefix(`/admin`)
      tls: {}

    to-pgadmin:
      entryPoints:
        - websecure
      rule: Host(`pgadmin.knh.cloud`)
      middlewares:
        - auth
      service: pgadmin

    to-portainer:
      service: portainer
      entryPoints:
        - websecure
      rule: Host(`portainer.knh.cloud`)
      tls: {}

    to-traefik:
      service: traefik
      entryPoints:
        - websecure
      middlewares:
        - auth
      rule: Host(`traefik.knh.cloud`)
      tls: {}
