http:
  services:
    fief:
      loadBalancer:
        servers:
          - url: http://fief:8000

    nocodb:
      loadBalancer:
        servers:
          - url: http://nocodb:8080

    pihole:
      loadBalancer:
        servers:
          - url: http://192.168.2.72:3001

    pgadmin:
      loadBalancer:
        servers:
          - url: http://pgadmin:80

    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000

    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080

    web:
      loadBalancer:
        servers:
          - url: http://nginx:80
