http:
  services:
    pihole:
      loadBalancer:
        servers:
        - url: "http://pihole:3001"

    portainer:
      loadBalancer:
        servers:
        - url: "http://portainer:9000"

    traefik:
      loadBalancer:
        servers:
        - url: "http://traefik:8080"
