http:
  services:
    web:
      loadBalancer:
        servers:
          - url: http://nginx:80
    nas:
      loadBalancer:
        servers:
          - url: http://192.168.2.72:8760
    pihole:
      loadBalancer:
        servers:
          - url: http://pihole:3001
    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080
