http:
  routers:
    to-web:
      entryPoints:
        - websecure
      rule: Host(`knh.cloud`)
      service: web

    to-pihole:
      entryPoints:
        - websecure
      rule: Host(`pihole.knh.cloud`)
      service: pihole

    to-portainer:
      entryPoints:
        - websecure
      rule: Host(`portainer.knh.cloud`)
      service: portainer

    to-traefik:
      entryPoints:
        - websecure
      rule: Host(`traefik.knh.cloud`)
      middlewares:
        - auth
      service: traefik

  middlewares:
    auth:
      basicAuth:
        usersFile: /config/usersfile

  services:
    web:
      loadBalancer:
        servers:
          - url: "http://nginx:80"
    pihole:
      loadBalancer:
        servers:
          - url: "http://pihole:3001"
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    traefik:
      loadBalancer:
        servers:
          - url: "http://traefik:8080"
