## scp -O -P 2222 portraefik/traefik/dynamic/*.yml sihuan@192.168.2.72:/share/dockume/portraefik/traefik/dynamic

http:
  routers:
    to-portainer:
      entryPoints:
        - websecure
      rule: Host(`portainer.vgate.keenetic.pro`)
      service: portainer

    to-traefik:
      entryPoints:
        - web
        - websecure
      rule: Host(`traefik.vgate.keenetic.pro`)
      service: traefik
