http:
  routers:
    to-traefik:
      entryPoints:
        - web
        - websecure
      rule: Host(`traefik.vgate.keenetic.pro`)
      service: traefik

    to-portainer:
      entryPoints:
        - websecure
      rule: Host(`portainer.vgate.keenetic.pro`)
      service: portainer

  middlewares:
    auth:
      basicAuth:
        usersFile: /config/usersfile

  services:
    portainer:
      loadBalancer:
        servers:
        - url: "http://portainer:9000"
    traefik:
      loadBalancer:
        servers:
        - url: "http://traefik:8080"
