http:
  services:
    traefik:
      loadBalancer:
        servers:
        - url: "http://traefik:8080"
    portainer:
      loadBalancer:
        servers:
        - url: "http://portainer:9000"
