---
# to avoid permission error
# start this compose stack by command
# UID=${UID} GID=${GID} docker compose up -d --build
# stop either
# UID=${UID} GID=${GID} docker compose down
version: "3.3"

services:
  resolver:
    build: ./resolver
    ports:
      - 53:53/udp
    networks:
      traefik:
        ipv4_address: 172.24.1.101

  authoritative:
    image: coredns/coredns:1.11.1
    user: ${UID}:${GID}
    volumes:
      - /share/dockume/infra/coredns/authoritative:/etc/coredns
    networks:
      traefik:
        ipv4_address: 172.24.1.102
    command: -conf /etc/coredns/Corefile

networks:
  traefik:
    external: true
