---
version: "3.3"

services:
  resolver:
    build: ./resolver
    ports:
      - 53:53/udp
    networks:
      local_dns:
        ipv4_address: 192.168.1.101

  authoritative:
    image: coredns/coredns:1.11.1
    user: ${UID}:${GID}
    volumes:
      - /share/dockume/infra/coredns/authoritative:/etc/coredns
    networks:
      local_dns:
        ipv4_address: 192.168.1.102
    command: -conf /etc/coredns/Corefile

networks:
  local_dns:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
