## path to place the file
## scp -O -P 2222 traefik/compose.yml sihuan@192.168.2.72:/share/dockume/infra/traefik
## docker compose up -d
## docker compose down
---
services:
  traefik:
    image: traefik:v3.2
    hostname: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /share/infra/traefik:/etc/traefik
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

# mkcert -key-file key.pem -cert-file cert.pem knh.cloud "*.knh.cloud" localhost 127.0.0.1 ::1
