---
services:
  pgadmin:
    image: dpage/pgadmin4:8.3
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5000:80"

volumes:
  pgadmin_data:
