## Static configuration
## path to place the file
## scp -P 2222 PORTAFIKconfig/traefik.yml sihuan@knhcloud:/share/dockume/portrafik/traefik/static

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /config/dynamic
    watch: true

certificatesResolvers:
  simple-resolver:
    acme:
      email: sihuannewrise@gmail.com
      storage: /config/letsencrypt/acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpchallenge:
        entrypoint: web

accesslog: true

log:
  level: ERROR