## Dynamic configuration
## path to place the file
## scp MODULAR/external/services.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/external
## scp MODULAR/external/services.yml sihuan@80.87.105.197:/home/sihuan/modular/dockume/traefik/external

http:
  routers:
    to-nginx:
      entryPoints:
        - "web"
        - "websecure"
      rule: "Host(`xwick.ru`)"
      tls:
        certResolver: simple-resolver
      service: nginx

    to-portainer:
      entryPoints:
        - "portainer"
      rule: "Host(`portainer.xwick.ru`)"
      tls:
        certResolver: simple-resolver
      service: portainer

    to-fief-server:
      entryPoints:
        - "fief"
      rule: "Host(`fief.xwick.ru`)"
      service: fief-server

    to-traefik:
      entryPoints:
        - "traefik"
      rule: "Host(`traefik.xwick.ru`)"
      service: traefik

  services:
    nginx:
      loadBalancer:
        servers:
        - url: "http://nginx:80"

    portainer:
      loadBalancer:
        servers:
        - url: "http://Portainer:9443"

    fief-server:
      loadBalancer:
        servers:
        - url: "http://fief-server:8000"

    traefik:
      loadBalancer:
        servers:
        - url: "http://proxy-server:8080"
