## Dynamic configuration
## path to place the file
## scp MODULAR/external/services.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/external
## scp MODULAR/external/services.yml sihuan@80.87.105.197:/home/sihuan/modular/dockume/traefik/external

http:
  routers:
    to-nginx:
      entryPoints:
        - "web"
        - "websecure"
      rule: "Host(`xwick.ru`)"
      # middlewares:
      #   - traefik-auth
      tls:
        certResolver: simple-resolver
        domains:
          - main: "xwick.ru"
            sans:
              - "*.xwick.ru"
      service: nginx

    to-portainer:
      entryPoints:
        - "web"
      rule: "Host(`portainer.xwick.ru`)"
      tls:
        certResolver: simple-resolver
        domains:
          - main: "xwick.ru"
            sans:
              - "*.xwick.ru"
      service: portainer

    to-fief-server:
      entryPoints:
        - "web"
      rule: "Host(`fief.xwick.ru`)"
      service: fief-server

    to-traefik:
      entryPoints:
        - "web"
      rule: "Host(`traefik.xwick.ru`)"
      tls:
        certResolver: simple-resolver
        domains:
          - main: "xwick.ru"
            sans:
              - "*.xwick.ru"
      service: traefik

  middlewares:
    traefik-auth:
      ipWhiteList:
        sourceRange: 172.18.0.0/16

  services:
    nginx:
      loadBalancer:
        servers:
        - url: "http://nginx:80"

    portainer:
      loadBalancer:
        servers:
        - url: "http://Portainer:9443"

    fief-server:
      loadBalancer:
        servers:
        - url: "http://fief-server:8000"

    traefik:
      loadBalancer:
        servers:
        - url: "http://proxy-server:8080"
