## Dynamic configuration
## path to place the file
## scp modular/external/services.yml sihuan@80.87.105.197:/home/sihuan/modular/dockume/traefik/external

http:
  routers:
    to-nginx:
      entryPoints:
        - "web"
        - "websecure"
      rule: "Host(`xwick.ru`)"
      tls: {}
      service: nginx

    to-fief-server:
      entryPoints:
        - "fief"
      rule: "Host(`xwick.ru`)"
      service: fief-server

    to-traefik:
      entryPoints:
        - "traefik"
      rule: "Host(`xwick.ru`)"
      service: traefik

  services:
    nginx:
      loadBalancer:
        servers:
        - url: "http://nginx:80"

    fief-server:
      loadBalancer:
        servers:
        - url: "http://fief-server:8000"

    traefik:
      loadBalancer:
        servers:
        - url: "http://proxy-server:8080"
