---
services:
  coder:
    image: ghcr.io/coder/coder:v2.14.2
    ports:
      - 7080:7080
    env_file: stack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    depends_on:
      coder-pg:
        condition: service_healthy

  coder-pg:
    image: postgres:16.1-alpine
    env_file: stack.env
    volumes:
      - /share/dockume/db/postgres/pg_multidb:/docker-entrypoint-initdb.d
      - coder_data:/var/lib/postgresql/data
    networks:
      - traefik
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-coder} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  coder_data:

networks:
  traefik:
    external: true
