# path to place the file
# scp -P 2222 config/traefik.yml sihuan@knhcloud:/volume4/dockume/traefik/config

# log:
#   level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: /external
    watch: true

entryPoints:
  web:
    address: knhcloud:80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
  websecure:
    address: :443

certificatesResolvers:
  simple-resolver:
    acme:
      email: sihuannewrise@gmail.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpchallenge:
        entrypoint: web

accesslog: true
