---
## path to place the file
## scp -P 2222 portraefik/traefik/compose.yml sihuan@knhcloud:/share/dockume/portraefik/traefik
version: "3.3"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - static:/etc/traefik
      - dynamic:/config/dynamic
      - /share/dockume/portraefik/traefik:/config
      - /share/dockume/portraefik/letsencrypt:/letsencrypt
    networks:
      - traefik

  portainer:
    image: portainer/portainer-ee:2.20.3
    container_name: portainer
    hostname: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/builtin/etc/certificate:/certs
      - /share/Docker/PortainerEE/data:/data
    networks:
      - traefik

volumes:
  static:
    driver: local
    driver_opts:
      type: none
      device: /share/dockume/portraefik/traefik/static
      o: bind
  dynamic:
    driver: local
    driver_opts:
      type: none
      device: /share/dockume/portraefik/traefik/dynamic
      o: bind

networks:
  traefik:
    external: true
