---
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio
    hostname: minio
    env_file: stack.env
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume4/minio/data:/data
    network_mode: host
