## scp traefik/config/static/traefik.yml root@192.168.2.91:/share/infra/traefik/static
## http://localhost:8080/api/rawdata

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
    # http:
    #   tls:
    #     certResolver: mkcert
        # certResolver: letsencrypt
        # domains:
        #   - main: knh.cloud
        #     sans:
        #       - fief.knh.cloud
        #       - nas.knh.cloud
        #       - nocodb.knh.cloud
        #       - pgadmin.knh.cloud
        #       - pihole.knh.cloud
        #       - portainer.knh.cloud
        #       - traefik.knh.cloud

api:
  dashboard: true
  insecure: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: /config/dynamic
    watch: true

# certificatesResolvers:
#   mkcert:
#     acme:
#       email: sihuannewrise@gmail.com
#       storage: /CA/mkcert-acme.json
#       caServer: https://__knh_cloud__/CA
#       tlsChallenge: true
#       httpChallenge:
#         entryPoint: web

#   letsencrypt:
#     acme:
#       email: sihuannewrise@gmail.com
#       storage: /letsencrypt/acme.json
#       caServer: https://acme-staging-v02.api.letsencrypt.org/directory # For testing, comment out for production
#       tlsChallenge: {}
      # httpChallenge:
      #   entryPoint: web

accessLog:
  true
  # filePath: /config/traefik-log.log
  # bufferingSize: 100 # Configuring a buffer of 100 lines
  # filters:
  #   statusCodes:
  #     - 400-499

log:
  level: ERROR
  # level: DEBUG" # set to INFO for production
