## scp -O -P 2222 traefik/config/static/traefik.yml sihuan@192.168.2.72:/share/dockume/infra/traefik/static
## http://localhost:8080/api/rawdata

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
    # http:
    #   tls:
    #     certResolver: letsencrypt
    #     domains:
    #       - main: knh.lan
    #         sans:
    #           - api.knh.lan
    #           - dev.knh.lan

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: /config/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /letsencrypt/acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpchallenge:
        entrypoint: web

accesslog: true

log:
  level: ERROR
