## scp traefik/config/static/traefik.yml root@192.168.2.91:/share/infra/traefik
## http://localhost:8080/api/rawdata

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443

api:
  dashboard: true
  insecure: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

accessLog: true
  # filePath: /etc/traefik/traefik.log
  # bufferingSize: 100   # Configuring a buffer of 100 lines
  # filters:
  #   statusCodes:
  #     - 400-499

log:
  level: ERROR
  # level: DEBUG" # set to INFO for production
