---
version: "3.3"

services:
  resolver:
    build: ./resolver
    ports:
      - 53:53/udp
    networks:
      local-dns:
        ipv4_address: 192.168.1.101

  authoritative:
    image: coredns/coredns
    command: -conf /etc/coredns/Corefile
    volumes:
      - /share/dockume/portraefik/dnsmasq/authoritative:/etc/coredns
    networks:
      local-dns:
        ipv4_address: 192.168.1.102

networks:
  local-dns:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
