---
services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file: stack.env
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"'
      timeout: 2s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/dockume/db/postgres/pg_multidb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.11
    depends_on:
      postgres:
        condition: service_started
    env_file: stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - traefik

  redis:
    container_name: fief_redis
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis_data:/data
    networks:
      - traefik

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  traefik:
    external: true
