## Dynamic configuration
# path to place the file
# scp -P 2222 external/services.yml sihuan@knhcloud:/volume4/dockume/traefik/external
# scp -P 2222 external/services.yml sihuan@192.168.2.72:/volume4/dockume/traefik/external

http:
  routers:
    to-nginx:
      entryPoints:
        - "web"
        - "websecure"
      rule: "Path(`/nginx`)"
      service: nginx
      tls:
        certResolver: simple-resolver
    to-pgdatabase:
      entryPoints:
        - "postgresql"
      rule: "HostSNI(`*`)"
      service: pgdatabase

  services:
    nginx:
      loadBalancer:
        servers:
        - url: "http://nginx:80"
    pgdatabase:
      loadBalancer:
        servers:
        - url: "http://postgresql:5432"
