## Dynamic configuration
## path to place the file
## scp -P 2222 external/services.yml sihuan@knhcloud:/volume4/dockume/traefik/external
## scp -P 2222 external/services.yml sihuan@192.168.2.72:/volume4/dockume/traefik/external

http:
  routers:
    to-nginx:
      entryPoints:
        - "web"
        - "websecure"
      rule: "Host(`192.168.2.72`)"
      tls: {}
      service: nginx

    to-fief-server:
      entryPoints:
        - "fief"
      rule: "Host(`192.168.2.72`)"
      service: fief-server

    to-traefik:
      entryPoints:
        - "traefik"
      rule: "Host(`192.168.2.72`)"
      service: traefik

  services:
    nginx:
      loadBalancer:
        servers:
        - url: "http://nginx:80"

    fief-server:
      loadBalancer:
        servers:
        - url: "http://fief-server:8000"

    traefik:
      loadBalancer:
        servers:
        - url: "http://proxy-server:8080"
