@baseUrl = https://nocodb.knh.cloud/api/v2
@authToken = IlHmicaslod_aRVFvXS6oUVj4eW-2NYqQzrSSZGF
@baseIdTelecom = pv56l9gyoi3fvae
@tableIdBeeline = mpmbm8wsz4g9cza

### Change field display title
PATCH {{baseUrl}}/meta/columns/cwsxtyjj361ox12
Content-Type: application/json
xc-token: {{authToken}}

{
  "column_name": "usagSmsActvAmt",
  "title": "SMS/MMS"
}

### meta API
GET {{baseUrl}}/meta/tables/{{tableIdBeeline}}/columns
Content-Type: application/json
xc-token: {{authToken}}
